### ISSUE TITLE
🐛 [BUG] - Neovim having trouble with plugins

### ISSUE THREAD

**Issue by SzymonSkoczylas** [Matt-FTW/dotfiles#14] opened 2024-06-02 08:15 UTC
### Did you check existing issues?

- [X] I have searched the existing issues of the repo
- [X] I have searched the existing issues of used programs related to this issue

### Description of the bug

```bash
Most of plugins in Neovim won't work after copying dotfiles to .config/nvim.
More information in screenshot.

I change some files (f.e. codesnap dir) from root to my user in .local/share/nvim/, because Neovim was throwing error that it hasn't had permissions and some of the warning went, but it still doesnt help me.
Also i use git config command that codesnap want and also no reaction.

Any ideas?
```

### Reproduction steps

```bash
1. Install dotfiles with README instruction.
2. Open Neovim
3. Neovim throwing fetch failed error with 60+ plugins
```

### Expected Behavior

All of the plugins to load

### Screenshots

```bash
https://ibb.co/dtgffD5
```

### Environment

```bash
Arch Linux, Hyprland
```

**Comment by Matt-FTW** [comment] 2024-06-02 10:36
It seems like I forgot to include a step in the installation guide haha.
Did you have some plugins installed already?
If you did, the issue has to be with the plugins you have installed in the .local/share/nvim dir. 
I'd recommend to backup instead of deleting, so make sure to execute the following commands:

```bash
mv ~/.local/share/nvim{,.bak}
mv ~/.local/state/nvim{,.bak}
mv ~/.cache/nvim{,.bak}
```

If you did not have them installed, then thats weird. Try deleting the lazy-lock.json file inside ~/.config/nvim and tell me if that helped you.

**Comment by SzymonSkoczylas** [comment] 2024-06-02 12:22
Oh and I forgot to mention. I'm getting "No specs found for module plugins.extras.lang.web.vue-3" lazy.nvim error.
After moving to backup my nvim config it's still a thing.

**Comment by Matt-FTW** [comment] 2024-06-02 15:42
To fix the vue issue, go to the lazyvim.json file inside ~/.config/nvim and delete the line that imports plugins.extras.lang.web.vue-3. The issue is fixed in upstream already.

So after backing up your nvim share folder and downloading all the plugins you still have the same problem?
What version of neovim are you running? Just in case, make sure is the last stable one (0.10).

**Comment by SzymonSkoczylas** [comment] 2024-06-02 16:06
Okay, everybody seems to work. I can launch neovim without wall of errors : ) 
Thanks a lot. I really enjoy your dotfiles. There's only a little I need to do to finish it.

PS.
I just needed to remove web.vue-3 from plugins to make it work and my version of nvim is 0.10.

**Comment by Matt-FTW** [comment] 2024-06-02 19:08
Glad it's working now!. Also thank you for your kind words <3

**Closed by Matt-FTW** 2024-06-02 19:08 UTC
Labels: bug
